### ISSUE TITLE
The version of quasar in the plugin is outdated!

### ISSUE THREAD

**Issue by fxjs** [panstromek/quasar-ide-helper#24]
This plugin is very good, we hope you can take the time to update to the latest quasar version, thank you!

**Comment by panstromek** [comment]
Wait, what do you mean? Is there some problem with it, does it crash or something? Because it is written to be version agnostic and doesn't explicitly depend on quasar.

**Comment by panstromek** [comment]
Yup, I just updated one of my Quasar projects and it runs on it with no problem, all helper files are generated just fine...

**Comment by panstromek** [comment]
@fxjs Can you be more specific about what's the problem? I didn't find any, so I'll close the issue unless you provide more information...
