### ISSUE TITLE
[IntelliJ] Not working with `QCalendar`

### ISSUE THREAD

**Issue by MartinX3** [panstromek/quasar-ide-helper#29]
My IntelliJ IDE with Volar for Typescript and the `Quasar Tools` Plugin still shows me `Unknown html tag q-calendar`.
The same for any other `QCalendar` component.

Of course I can compile and run the website just fine and see the calendar.

I also don't know if I forgot to install something.

**Comment by panstromek** [comment]
This ide helper is no longer needed, everything it does was already implemented by JetBrains natively, you should report this to the IDE plugins directly ([Vue](https://youtrack.jetbrains.com/issues/WEB?q=%23vue) plugin or [Quasar tools](https://github.com/knusperleicht/intellij-quasar) plugin) , or to QCalendar project.. 

QCalendar is not an official Quasar component, so it might not be included in the analysis if the component is not exported in some IDE-understandble way, or if it doesn't have `web-types` included in the package (like Quasar does). 

(note that this is helper not an IntelliJ plugin, and it has nothing to do with Quasar Tools or Volar, it's just a helper file generator).
