### ISSUE TITLE
[Feature request] To make helper for I18n internalization strings.

### ISSUE THREAD

**Issue by DmitrijOkeanij** [panstromek/quasar-ide-helper#3]
When I type `$i18n.t("loginOrRegisterMenu.enter")` it's easy to make typo in words. The way is to copy paste from language file.

But it will simplify flow if helpers appeared on typing words in `$i18n.t`.

**Comment by panstromek** [comment]
This is probably not so simple I guess, but I see a possible way to do it.

 - [ ] Collect all possible strings that can be valid arguments for `$i18n.t`, `$t` or other translation functions.
 - [ ] Render all those strings as types in JSDoc comment or typescript file together with "fake" definition translation functions or additional typescript typing. Something like:

```js

Vue.prototype.$i18n = {
  /**
   *
   * @param {( 'loginOrRegisterMenu.enter' | 'anotherTranslation') } key
   */
  t (key) {

  }
}

```
 - [ ] And the hardest part: Hook into Quasar dev process and regenerate this file if and only if translation files change.

Without the last step, we could maybe just add a new command that will generate the file.

If someone wants to take a shot and make a PR, feel free to do so (comment here to let us know ;)).

**Comment by DmitrijOkeanij** [comment]
Hi.
I am not sure that I need what I wrote before.
Mabe just to close this?
I use i18n.
But I use my custom implementation with my  this.$tl function.
The 2 thing is that i18n as it is in Quasar now is not very effective because it recalculate on every rerender and has no cache.

**Comment by DmitrijOkeanij** [comment]
I think that in Quasar needed some patch or some upgrades to localization system.
But if I do so on my project as I did. I am not using classic this.&t and if ide.helper works with this it will breakes, so I think just to close issue?

**Comment by DmitrijOkeanij** [comment]
I do not want to waste your time.

**Comment by panstromek** [comment]
Another thing is that this is more related to `vue-i18n` than Quasar, it would make sense make it in a separate package. You're right, let's close this 😉
