### ISSUE TITLE
[Feature request] [Question] Is it possible to insert attributes with out values?

### ISSUE THREAD

**Issue by DmitrijOkeanij** [panstromek/quasar-ide-helper#4]
I try to add padding attribute to Qpage with IDE.
It adds as `<QPage padding="">`.

Is it possible to add as just  `<QPage padding>`. Without `=""`.

Also this question is [Feature request] if it is possible.

**Comment by panstromek** [comment]
It is not - this is default behaviour in intellij that I can't change. You can look in menu to disable automatic `""` but it will still add `=`.

I actually tried to fiddle around with this a lot and I haven't found a way to convince IDEA to not add it...

**Comment by panstromek** [comment]
BUT - you can make a feature request in IntelliJ YouTrack 😉

**Comment by DmitrijOkeanij** [comment]
May be to feature request to JetBrains?

**Comment by panstromek** [comment]
yup ;) I tried to find if it is possible to contribute it to the Vue plugin (because it affects all boolean props in Vue project) , but it's not so straightforward...

**Comment by panstromek** [comment]
ok, it's actually already reported twice https://youtrack.jetbrains.com/issue/WEB-34383

**Comment by panstromek** [comment]
so go upvote it ;)

**Comment by DmitrijOkeanij** [comment]
I added here my like

**Comment by DmitrijOkeanij** [comment]
May be to call others Quasarians to upvote?
