### ISSUE TITLE
router-link highlight

### ISSUE THREAD

**Issue by DmitrijOkeanij** [panstromek/quasar-ide-helper#5]
IDE do not understand Router link 

![image](https://user-images.githubusercontent.com/10674646/54023440-02de2400-41a6-11e9-8837-fa750e2d5b3e.png)

**Comment by panstromek** [comment]
Add Vue router as a library ;) it's described in the readme in "prerequisites" ;)

**Comment by DmitrijOkeanij** [comment]
Thanks!
