### ISSUE TITLE
[Feature request] To make helper for importing stylus styles

### ISSUE THREAD

**Issue by DmitrijOkeanij** [panstromek/quasar-ide-helper#6]
Now importing styles is really unclear in Quasar.

1. Dont know how to import app.styl
2. To import quasar.varibles.styl i need to write  @import '~quasar-variables'. In first place this is `.` dot, in secont `-`.

Feature request to make helper to import styles.
And feture request to Quasar to make easy and clear system to import styles.

**Comment by panstromek** [comment]
I am not sure if I can do something with this 🤔 , I will look at that

**Comment by panstromek** [comment]
Import is not needed anymore, so I am closing this.
