### ISSUE TITLE
[Request] To make Rider understand webpack config file

### ISSUE THREAD

**Issue by DmitrijOkeanij** [panstromek/quasar-ide-helper#9]
If I have this section in quasar.conf.js

```
  extendWebpack (cfg) {
        cfg.resolve.modules.push(path.resolve('./src'));
        cfg.resolve.modules.push(path.resolve('./src/modules'));
        cfg.resolve.modules.push(path.resolve('./src/components'));
        cfg.resolve.modules.push(path.resolve('./src/services'));
      }
    },
```

Webpack resolver pathes with this definotions.
To make Rider understand pathes I made this file manualy.

```
'use strict'

const path = require('path')

module.exports = {
  resolve: {
    modules: [
      path.resolve(__dirname, './src'),
      path.resolve(__dirname, './src/modules'),
      path.resolve(__dirname, './src/components'),
      path.resolve(__dirname, './src/services')
    ]
  }
}
```

And this is no problem.
But may be to make it inside ide-helper?
Or not directly this but make full compiled webpack configuration file to make Rider understand all connecting webpack config?

**Comment by panstromek** [comment]
I actually already do the same thing. I want to integrate it inside ide-helper, too ;)

The problem is that idea doesn't recognize it automatically (at least in my case), so I need to mess around with `.idea` folder which I am not really sure I should do...

I would also like to render all Quasar webpack config with all aliases, which means I need to integrate it into the pipeline, somehow. I need to figure it out.

But thx ;) it's on my radar (just been very busy with work ATM)

**Comment by DmitrijOkeanij** [comment]
Mabe to make webpack config file and to put in some dir and nothing more.
User can manually add in Ide settings.
Also this is helpfull because many people interesting in full result webpack config.

Adn may be to make custom ext command to register this result webpack file to IDE.
Not automatic, but manually with run ccomand.

**Comment by DmitrijOkeanij** [comment]
Idia as I think can recognize webpack config file if it is inside root dir? I am not cure. In my case I have custom file name and it did not recognize, but if file name is standart...

**Comment by DmitrijOkeanij** [comment]
Or may be when run ask user to integrate or not to integrate?

**Comment by DaedalusDev** [comment]
> Idia as I think can recognize webpack config file if it is inside root dir? I am not cure. In my case I have custom file name and it did not recognize, but if file name is standart...

You can specify a webpack file path in `Files -> Settings -> Languages & Frameworks -> Javascript -> Webpack`. You are right, the default location is `<project_dir>/webpack.conf.js`.

If your file still valid, Idea will type for `Module resolution rules from webpack.config.js are now used for coding assistance.` in Event log.

**Comment by DmitrijOkeanij** [comment]
So I think the best way is just to generate `webpack.conf.js` in root dir, and notify user that this file is not for configuring build process but to help Idea, and to show webpack result for user purposes.

**Comment by panstromek** [comment]
Quick workaround for now:

```js
   extendWebpack (cfg) {
        if (!fs.existsSync('webpack.config.js')) {
          fs.writeFileSync('webpack.config.js', `
/* eslint-disable */
/**
 * DON'T EDIT THIS FILE!!
 *
 * This file is generated to help WebStorm resolve Webpack aliases. It is never run in the app.
 * If you need to extend your webpack config, put your code in quasar.conf.js into extendWebpack function
 */
module.exports = ${JSON.stringify(cfg)}
`)
        }
      }
```

I want to integrate it when I have some time. If someone wants to try it, just PR (comment here to let us know)

**Comment by panstromek** [comment]
I think this is done (for the next release) - I couldn't actually find where Idea stores the setting for the webpack config, seems like there is no mention of it in `.idea` folder. 

I guess I'll just add a notice for user to set it manually (I don't feel right about messing around with `.idea` folder anyway - it's internal to for the IDE and it's structure and format can change at any time)
